apiVersion: v1
kind: Service
metadata:
  name: expense-backend
  namespace: expense-tracker
spec:
  type: NodePort
  selector:
    app: expense-backend
  ports:
    - name: http
      port: 9876
      targetPort: 9876
      nodePort: 30976
