apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-backend
  namespace: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-backend
  template:
    metadata:
      labels:
        app: expense-backend
    spec:
      imagePullSecrets:
        - name: nexus-regcred
      containers:
        - name: expense-backend
          image: 192.168.56.30/expense-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9876
          env:
            - name: FRONTEND_ORIGIN
              value: 'http://NODE_IP:30080'
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service.postgres.svc.cluster.local:5432/mydb
            - name: SPRING_DATASOURCE_USERNAME
              value: admin
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: DB_POD_NAME
              value: postgres-0
