apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-frontend
  namespace: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-frontend
  template:
    metadata:
      labels:
        app: expense-frontend
    spec:
      imagePullSecrets:
        - name: nexus-regcred
      containers:
        - name: expense-frontend
          image: 192.168.56.30/expense-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
